import Studio from './Studio'

const StudioList = () => {
  const list: StudioList = {
    '#': [
      '100studio',
      '10Gauge',
      '1IN',
      '2:10 AM Animation',
      '33 Collective',
      '5 Inc.',
      '6pucks',
      '7doc',
      '81 Produce',
      '8bit'
    ],
    A: [
      'A-1 Pictures',
      'A-Line',
      'A-Real',
      'A.C.G.T.',
      'ACC Production',
      'ACiD FiLM',
      'AHA Entertainment',
      'AIC',
      'AIC ASTA',
      'AIC Build',
      'AIC Classic',
      'AIC Frontier',
      'AIC PLUS+',
      'AIC Project',
      'AIC Spirits',
      'AIC Takarazuka',
      'AION Studio',
      'AMGA',
      'ANIDO FILM',
      'APPP',
      'AQUA ARIS',
      'ARCUS',
      'ARECT',
      'ASK Animation Studio',
      'AT-2',
      'AXsiZ',
      'Academy Productions',
      'Acca effe',
      'Actas',
      'Adonero',
      'Agent 21',
      'Ai Si Animation Studio',
      'Ai Yume Mai',
      'Aiko',
      'Aiti St.',
      'Ajia-do',
      'Akatsuki',
      'Albacrow',
      'Alfred Imageworks',
      'Alice Production',
      'Alpha Animation',
      'Amarcord',
      'Amineworks',
      'An DerCen',
      'Angle',
      'Anima',
      'Anima&Co.',
      'Animaruya',
      'Animation 21',
      'Animation 501',
      'Animation Do',
      'Animation Lab Japan',
      'Animation Planet',
      'Animation Staff Room',
      'Anime Antenna Iinkai',
      'Anime Beans',
      'Anime R',
      'Anime Tokyo',
      'Ankama Animations',
      'Annapuru',
      'Anon Pictures',
      'Anpro',
      'Arch',
      'Arcs Create',
      'Arcturus',
      'Ark',
      'Arms',
      'Artland',
      'Artmic',
      'Arvo Animation',
      'Asahi Production',
      'Ascension',
      'Ashi Productions',
      'Asmik Ace',
      'Assez Finaud Fabric',
      'Asura Film',
      'AtelierPontdarc',
      'Atorie A.B.C.',
      'Atti Production',
      'Au Praxinoscope',
      'Aubec',
      'Aurora Animation',
      'Aurum Production',
      'Automatic Flowers Studio',
      'Azeta Pictures',
      'animate Film',
      'asread.'
    ],
    B: [
      'B&T',
      'B.CMAY PICTURES',
      'BUG FILMS',
      'BUILD DREAM',
      'BYMENT',
      'Bakken Record',
      'Bandai Namco Filmworks',
      'Bandai Namco Pictures',
      'Bandai Spirits',
      'Bandai Visual',
      'Barnum Studio',
      'BeSTACK',
      'Beat Frog',
      'Bebow',
      'Bee Media',
      'Bee Train',
      'Beijing Enlight Pictures',
      'Beijing Huihuang Animation Company',
      'Benlai Pictures',
      'Bibury Animation CG',
      'Bibury Animation Studios',
      'Big Bang',
      'Big Firebird Culture',
      'Big Wing',
      'Bigcat Studio',
      'Blade',
      'Blue Cat',
      'Blue Note',
      'Blue bread',
      'Bones',
      'Borutong',
      'Bouncy',
      'Boyan Pictures',
      "Brain's Base",
      'BreakBottle',
      'Brians Film',
      'Bridge',
      'Brio Animation',
      'Buemon'
    ],
    C: [
      'C and R',
      'C&S Production',
      'C-Station',
      'C2C',
      'CANDY BOX',
      'CANON RECORDINGS',
      'CCTV Animation',
      'CG Year',
      'CGCG Studio',
      'CHOCOLATE',
      'CLAP',
      'CMAY Animation',
      'CUCURI',
      'Cafe de Jeilhouse',
      'Calf Studio',
      'Caviar',
      'Central Animation Studio',
      'Changchun Unity of Knowledge and Action Animation',
      'Chaos Project',
      'Charaction',
      "Children's Playground Entertainment",
      'Chiptune',
      'Chongzhuo Animation',
      'Chosen',
      'ChuChu',
      'Circle Tribute',
      'Circus Production',
      'Cloud Art',
      'Cloud Hearts',
      'CloverWorks',
      'CoMix Wave Films',
      'Coastline Animation Studio',
      'Code',
      'Collaboration Works',
      'Colored Pencil Animation',
      'Colored Pencil Animation Japan',
      'Comma Studio',
      'Composition Inc.',
      'Concept Films',
      'Congrong Film',
      'Congzhuo Animation',
      'Connect',
      'Contrail',
      'Craftar Studios',
      'Creative Power Entertaining',
      'Creators Dot Com',
      'Creators in Pack',
      'Creatures Inc.',
      'Cutie Bee',
      'CyberConnect2',
      'Cyclone Graphics',
      'CygamesPictures',
      'cogitoworks'
    ],
    D: [
      'D & D Pictures',
      'D.A.S.T.',
      'DAX Production',
      'DC Impression Vision',
      'DLE',
      'DMM.futureworks',
      'DOGA Productions',
      'DR Movie',
      'DRAWIZ',
      'Daewon Media',
      'Dai-Ichi Douga',
      'Dancing CG Studio',
      'DandeLion Animation Studio',
      'Dangun Pictures',
      'Darts',
      'Datama Film',
      'Daume',
      'David Production',
      'Dawn Animation',
      'Dazzling Star',
      'Deck',
      'Decovocal',
      'Delight Animation',
      'Delpic',
      'Digital Frontier',
      'Digital Media Lab',
      'Digital Network Animation',
      'Diomedéa',
      'Directions',
      'Djinn Power',
      'Doga Kobo',
      'Dongwoo A&E',
      'Dongyang Animation',
      'Drawing and Manual',
      'Dream Entertainment',
      'Drive',
      'Durufix',
      'Dyna Method',
      'Dynamic Planning',
      'Dynamo Pictures',
      'd00r works',
      'domerica',
      'drop',
      'dwarf'
    ],
    E: [
      'E&G Films',
      'E&H Production',
      'EDP graphic works',
      'EKACHI EPILKA',
      'EMT Squared',
      'ENGI',
      'EOEO System',
      'Eallin',
      'Earth Design Works',
      'East Fish Studio',
      'Echo',
      'Echoes',
      'Egg',
      'Egg Firm',
      'Eiken',
      'Ekakiya',
      'Ekura Animal',
      'Emon',
      'Encourage Films',
      'Enishiya',
      'Enjin Productions',
      'Enzo Animation',
      'Eshoya Honpo',
      'Ether Kitten',
      'Executive Decision',
      'Ezόla',
      'evg'
    ],
    F: [
      'FILMONY',
      'FIREBUG',
      'FLAGSHIP LINE',
      'FOREST Hunting One',
      'FUNNY MOVIE',
      'Fantawild Animation',
      'Fanworks',
      'Felix Film',
      'Fengyun Animation',
      'Fenz',
      'Fever Creations',
      'Fifth Avenue',
      'Filmlink International',
      'Flat Studio',
      'Flavors Soft',
      'Flint Sugar',
      'Flying Ship Studio',
      'Foch Films',
      'Four Some',
      'Front Line',
      'Frontier One',
      'Frontier Works',
      'Fuji TV',
      'Fukushima Gaina',
      'Future Planet',
      'feel.',
      'flag Co.',
      'foodunited.'
    ],
    G: [
      'G&G Entertainment',
      'G-Lam',
      'G-angle',
      'G.P Entertainment',
      'GA-CREW',
      'GANSIS',
      'GARDEN LODGE',
      'GAV Video',
      'GEMBA',
      'GIFTanimation',
      'GRIZZLY',
      'GUMBLAB',
      'Gaina',
      'Gainax',
      'Gainax Kyoto',
      'Gakken',
      'Gakken Eigakyoku',
      'Gallop',
      'Gambit',
      'Garden Culture',
      'Garyuu Studio',
      'Gathering',
      'Geek Toys',
      'Gekkou',
      'Genco',
      'General Entertainment',
      'Geno Studio',
      'Giga Production',
      'Ginga Ya',
      'GoHands',
      'Gonzino',
      'Gonzo',
      'Gosay Studio',
      'Goto Inc.',
      'Graphinica',
      'Gravity Well',
      'Green Monster Team',
      'Griot Groove',
      'Grom',
      'Group TAC',
      'Grouper Productions',
      'Gunners',
      'Guo Pengzi Studio',
      'Guton Animation Studio',
      'Gyorai Eizo Inc.'
    ],
    H: [
      'HIDEHOMARE',
      'HM Heros',
      'HMCH',
      'HORNETS',
      'HOTZIPANG',
      'HS Pictures Studio',
      'Hai An Xian Donghua Gongzuo Shi',
      'Hal Film Maker',
      'Hananona Studio',
      'Hand to Mouse.',
      'Haneda xR Studio',
      'Haoliners Animation League',
      'Happy Elements',
      'Hayabusa Film',
      'HeART-BIT',
      'Heart & Soul Animation',
      'Heewon Entertainment',
      'High Energy Studio',
      'Himajin Planning',
      'Hiro Media',
      'Hololive Production',
      'Hong Ying Animation',
      'Hoods Drifters Studio',
      'Hoods Entertainment',
      'Horannabi',
      'HoriPro',
      'Hotline',
      'Hu Po Donghua',
      'HuaDream',
      'HuaMei Animation',
      'Hurray!',
      'Husio Studio',
      'happyproject',
      'helo.inc'
    ],
    I: [
      'I was a Ballerina',
      'I-move',
      'I.Gzwei',
      'I.Toon',
      'IKK Room',
      'ILCA',
      'IMAGICA Lab.',
      'Ice Butter',
      'Idea Factory',
      'Idol',
      'Image House',
      'Image Kei',
      'Imagestone Inc.',
      'Imagica',
      'Imagica Digitalscape',
      'Imagica Imageworks',
      'Imagin',
      'Imagineer',
      'Inc.',
      'Indeprox',
      'Indivision',
      'Infinity Vision',
      'Inugoya',
      'Irawias',
      'Ishibashi Planning',
      'Ishikawa Pro',
      'Ishimori Entertainment',
      'Issen',
      'Itasca Studio',
      'Iyasakadou Film',
      'iDRAGONS Creative Studio',
      'ixtl'
    ],
    J: [
      'J.C.F.',
      'J.C.Staff',
      'J.K.I',
      'JCF',
      'JJJOY Animation Studios',
      'JM Animation',
      'JOF',
      'Japan Taps',
      'Japan Vistec',
      'Jichitai Anime',
      'Jinnan Studio',
      'Jinnis Animation Studios',
      'Joicy Studio',
      'Joker Films',
      'Jumondo',
      'Jumonji'
    ],
    K: [
      'K-Factory',
      'KAGAYA Studio',
      'KIZAWA Studio',
      'KJJ Animation',
      'KKC Animation Production',
      'KOO-KI',
      'KSS',
      'Kaca Entertainment',
      'Kachidoki Studio',
      'Kaeruotoko Shokai',
      'Kami Kukan',
      'Kamikaze Douga',
      'Kamio Japan',
      'Kamitsubaki Studio',
      'Kanaban Graphics',
      'Kaname Productions',
      'Kantou Douga Kai',
      'Karaku',
      'Karasfilms',
      'Kate Arrow',
      'Kazami Gakuen Koushiki Douga-bu',
      'Kazuki Production',
      'Keica',
      'Kenji Studio',
      'Kent House',
      'KeyEast',
      'Keyring',
      'Khara',
      'Kigumi',
      'Kinema Citrus',
      'Kino Production',
      'Kitty Film Mitaka Studio',
      'Knack Productions',
      'Kokusai Eigasha',
      'Kuai Ying Hu Yu',
      'Kung Fu Frog Animation',
      'Kuri Jikken Manga Kobo',
      'Kusama Art',
      'Kyoto Animation',
      'Kyotoma',
      'Kyushu Network Animation'
    ],
    L: [
      'LAN Studio',
      'LB Commerce',
      'LEVELS',
      'LICO',
      'LIDENFILMS',
      'LIDENFILMS Kyoto Studio',
      'LIDENFILMS Osaka Studio',
      'LMD',
      'LX Animation Studio',
      'LandQ studios',
      'Lapin Track',
      'Larx Entertainment',
      'Lay-duce',
      'Lead',
      'Lerche',
      'Lesprit',
      'Liber',
      'Liberty Animation Studio',
      'Lide',
      'Life Work',
      'Light Chaser Animation Studios',
      'Lilix',
      'Lingsanwu Animation',
      'Live2D Creative Studio',
      'Liyu Culture',
      'L²Studio',
      'l-a-unch・BOX'
    ],
    M: [
      'M&M',
      'M.S.C',
      'MAPPA',
      'MASTER LIGHTS',
      'MAT',
      'MB planning',
      'MI',
      'MMDGP',
      'MMT Technology',
      'MORIE Inc.',
      'Maboroshi Koubou',
      'Mad Box',
      'Madhouse',
      'Magia Doraglier',
      'Magic Bus',
      'Magma Studio',
      'Maho Film',
      'Majin',
      'Makaria',
      'Making Animation',
      'Manglobe',
      'Marine Entertainment',
      'Maro Studio',
      'Marone',
      'Marui Group',
      'Marvy Jack',
      'Marza Animation Planet',
      'Maxilla',
      'Melissa',
      'Meltdown',
      'Meruhensha',
      'Mikimoto Production',
      'Mili Pictures',
      'Milky Cartoon',
      'Millepensee',
      'Mimoid',
      'Minakata Laboratory',
      'Minami Machi Bugyousho',
      'Mippei Eigeki Kiryuukan',
      'Mirai Film',
      'Mirai Fusion',
      'Miyu Productions',
      'MoMo Production',
      'Mokai Technology',
      'Momoi Planning',
      "Monster's Egg",
      'MontBlanc Pictures',
      'MooGoo',
      'Mook Animation',
      'Mook DLE',
      'Moss Design Unit',
      'Motion Magic',
      'Mouse',
      'Mousou Senka',
      'Movic',
      'Mushi Production',
      'Myung Films',
      'monofilmo'
    ],
    N: [
      'NANON CREATIVE',
      'NAZ',
      'NHK',
      'NHK Art',
      'NHK Enterprises',
      'Nakamura Production',
      'Namu Animation',
      'Neft Film',
      'Nekonigashi Inc.',
      'Network Kouenji Studio',
      'New Deer',
      'New Generation',
      'Next Media Animation',
      'Nexus',
      'Nice Boat Animation',
      'Nihikime no Dozeu',
      'Nihon Ad Systems',
      'Nippon Animation',
      'Nippon Ramayana Film Co.',
      'Nomad',
      'Noovo',
      'Nostalook',
      'Nur',
      'Nut'
    ],
    O: [
      'OB Planning',
      'OLM',
      'OLM Digital',
      'OLM Team Kato',
      'OLM Team Yoshioka',
      'ORADA COMPANY',
      'ORENDA',
      'OTOIRO',
      'OZ',
      'October Media',
      'Oddjob',
      'Odolttogi',
      'Office AO',
      'Office DCI',
      'Office No. 8',
      'Office Nobu',
      'Office Take Off',
      'Office Takeout',
      'Oh! Production',
      'Okumaza',
      'Okuruto Noboru',
      'Olive Studio',
      'Onion Studio',
      'Onionskin',
      'Opera House',
      'Orange',
      'Ordet',
      'Oriental Creative Color',
      'Original Dream',
      'Original Force',
      'Otogi Production',
      'Overlap',
      'Oxybot',
      'Oyster',
      'Oz Inc.'
    ],
    P: [
      'P core',
      'P.A. Works',
      'P.I.C.S.',
      'PERIMETRON',
      'PINE JAM',
      'PONOS Corporation',
      'PP Project',
      'PPM',
      'PRA',
      'Painting Dream',
      'Palm Studio',
      'Pancake',
      'Panda Factory',
      'Panmedia',
      'Paper Animation',
      'Paper Plane Animation Studio',
      'Passion Paint Animation',
      'Passione',
      'Pastel',
      'Pb Animation Co. Ltd.',
      'Peak Hunt',
      'Phoenix Entertainment',
      'Picograph',
      'Picona',
      'Picture Magic',
      'Pie in the sky',
      'Pierrot',
      'Pierrot Plus',
      'Piko Studio',
      'Pink Cat',
      'Piso Studio',
      'Planet',
      'Planet Cartoon',
      'Planet Nemo Animation',
      'Platinum Vision',
      'Plum',
      'Plus Heads',
      'Pmats9 studio',
      'PoRO',
      'Point Pictures',
      'Pollyanna Graphics',
      'Poly Animation',
      'Polygon Pictures',
      'Poncotan',
      'Pony Canyon',
      'Pops Inc.',
      'Potato House',
      'Primastea',
      'PrimeTime',
      'Production +h.',
      'Production D.M.H',
      'Production GoodBook',
      'Production I.G',
      'Production IMS',
      'Production Reed',
      'Project No.9',
      'Project Team Muu',
      'Project Team Sarah',
      'Public & Basic',
      'Pure Arts',
      'Purple Cow Studio Japan',
      'Puzzle Animation Studio Limited',
      'pH Studio',
      'production doA'
    ],
    Q: [
      'Qianqi Animation',
      'Qingxiang Culture',
      'Qiying Animation',
      'Qiyuan Yinghua',
      'Quad',
      'Qualia Animation',
      'Qubic Pictures',
      'Quebico',
      'Queen Bee',
      'Quyue Technology',
      'Qzil.la'
    ],
    R: [
      'RAMS',
      'REALTHING',
      'RG Animation Studios',
      'Rabbit Gate',
      'Rabbit Machine',
      'Radix',
      'Red Dog Culture House',
      'Reiki Eyes Animation',
      'Remic',
      'Revoroot',
      'Rikuentai',
      'Ripple Film',
      'Ripromo',
      'Rising Force',
      'Robot Communications',
      'Rocen',
      'Rockwell Eyes',
      'Romanov Films',
      'Ruo Hong Culture',
      "Ryuu M's"
    ],
    S: [
      'SAMG Entertainment',
      'SANZIGEN',
      'SBS TV Production',
      'SEK Studios',
      'SELFISH',
      'SIDO LIMITED',
      'SIGNIF',
      'SILVER LINK.',
      'SJYNEXCUS',
      'SPEED',
      "STUDIO6'oN",
      'Saber Project',
      'Saetta',
      'Saigo no Shudan',
      'Sakura Create',
      'Samsara Animation Studio',
      'Sanctuary',
      'Sankaku',
      'Sanrio',
      'Sanrio Digital',
      'Satelight',
      'Schoolzone',
      'Science SARU',
      'Scooter Films',
      'Sega Interactive',
      'Seven',
      'Seven Arcs',
      'Seven Arcs Pictures',
      'Seven Stone Entertainment',
      'Shaft',
      'Shanghai Animation Film Studio',
      'Shanghai Hippo Animation',
      'Sharefun Studio',
      'Shelty',
      'Shengguang Knight Culture',
      'Shengying Animation',
      'Shenman Entertainment',
      'Shimogumi',
      'Shin-Ei Animation',
      'Shindeban Film',
      'Shinjukuza',
      'Shinkuukan',
      'Shion',
      'Shirogumi',
      'Shochiku Animation Institute',
      'Shogakukan Music & Digital Entertainment',
      'Shueisha',
      'Shuka',
      'Shura',
      'Signal.MD',
      'Silver',
      'Slow Studio',
      'Soeishinsha',
      'Soft Garage',
      'Sola Digital Arts',
      'Sonsan Kikaku',
      'Sotsu',
      'Sovat Theater',
      'Soyep',
      'Space Neko Company',
      'Space-X',
      'Sparkly Key Animation Studio',
      'Sparky Animation',
      'Speed Inc.',
      'Spell Bound',
      'Spooky graphic',
      'Spoon',
      'Sprite Animation Studios',
      'Square Enix Visual Works',
      'Square Pictures',
      'Staple Entertainment',
      'Starry Cube',
      'Steamworks',
      'Stereotype',
      "Steve N' Steven",
      'Stingray',
      'Story Effect',
      'StoryRiders Co. Ltd.',
      'Strawberry Meets Pictures',
      'Studio 1st',
      'Studio 3Hz',
      'Studio 4°C',
      'Studio 88',
      'Studio 9 Maiami',
      'Studio A-CAT',
      'Studio A. Craft',
      'Studio Add',
      'Studio Animal',
      'Studio B&M',
      'Studio Bind',
      'Studio Binzo',
      'Studio Blanc.',
      'Studio Bogey',
      'Studio Boogie Nights',
      'Studio CA',
      'Studio Chizu',
      'Studio Coa',
      'Studio Colorido',
      'Studio Comet',
      'Studio Core',
      'Studio Crocodile',
      'Studio D-Volt',
      'Studio DURIAN',
      'Studio Dadashow',
      'Studio Daisy',
      'Studio Deen',
      'Studio Dolphin Night',
      'Studio Egg',
      'Studio Elle',
      'Studio Eromatick',
      'Studio Fantasia',
      'Studio Flad',
      'Studio Flag',
      'Studio Fusion',
      'Studio G-1Neo',
      'Studio GOONEYS',
      'Studio Gadget',
      'Studio Gazelle',
      'Studio Ghibli',
      'Studio Gohan',
      'Studio Gokumi',
      'Studio Gram',
      'Studio Guts',
      'Studio HUIT',
      'Studio Hakk',
      'Studio Hibari',
      'Studio Himalaya',
      'Studio Hokiboshi',
      'Studio Izena',
      'Studio Jam',
      'Studio Jemi',
      'Studio Jin',
      'Studio Junio',
      'Studio Kafka',
      'Studio Kai',
      'Studio Kajino',
      'Studio Kelmadick',
      'Studio Khronos',
      'Studio Kikan',
      'Studio Kingyoiro',
      'Studio Korumi',
      'Studio Kyuuma',
      'Studio Lings',
      'Studio Live',
      'Studio M2',
      'Studio March',
      'Studio Massket',
      'Studio Matomo',
      'Studio Matrix',
      'Studio Meditation With a Pencil',
      'Studio Mir',
      'Studio Moriken',
      'Studio Nanahoshi',
      'Studio Nuck',
      'Studio OX',
      'Studio Palette',
      'Studio Pastoral',
      'Studio Pivote',
      'Studio Ponoc',
      'Studio Ppuri',
      'Studio Prokion',
      'Studio PuYUKAI',
      'Studio Ranmaru',
      'Studio Rikka',
      'Studio Shelter',
      'Studio Sign',
      'Studio Signal',
      'Studio Signpost',
      'Studio Sota',
      'Studio Soul',
      'Studio Take Off',
      'Studio Ten',
      'Studio Ten Carat',
      'Studio Tumble',
      'Studio UGOKI',
      'Studio Unicorn',
      'Studio VOLN',
      'Studio Vandal',
      'Studio W.Baba',
      'Studio Wombat',
      'Studio World',
      'Studio Z5',
      'Studio Zero',
      'Studio! Cucuri',
      'StudioRF Inc.',
      'StudioXD',
      'Sublimation',
      'Success Corp.',
      'Sugar Boy',
      'Sumomo Film',
      'Suna Kouhou',
      'Sunflowers',
      'Sunny Side Up',
      'Sunrise',
      'Sunrise Beyond',
      'Sunwoo Entertainment',
      'Super Brain',
      'Super Normal Studio',
      'Suspenders',
      'Suzuki Mirano',
      'Synergy Japan',
      'SynergySP',
      'studio MOTHER',
      'studio NAGURI',
      'studio YOG',
      'studio hb'
    ],
    T: [
      'T-Rex',
      'T.P.O',
      'TANOsim',
      'TCJ',
      'TEC',
      'THINGS.',
      'THINKR',
      'TMS Entertainment',
      'TNK',
      'TOCSIS',
      'TOHO animation',
      'TOHO animation STUDIO',
      'TROYCA',
      'TUBA',
      'TYMOTE',
      'TYO Animations',
      'Taikong Works',
      'Takahashi Studio',
      'Takara Tomy A.R.T.S',
      'Tama Production',
      'Tamura Shigeru Studio',
      'Tanglin Culture',
      'Taomee',
      'Tatsunoko Production',
      'Team TillDawn',
      'Team YokkyuFuman',
      'Tear Studio',
      'Teatro Nishi Tokyo Studio',
      'Tecarat',
      'Tele-Cartoon Japan',
      'Telecom Animation Film',
      'Telescreen',
      'Ten Tails Animation',
      'Tengu Kobo',
      'Tezuka Productions',
      'The Answer Studio',
      'The Monk Studios',
      'The Village of Marchen',
      'Think Corporation',
      'Three-d',
      'Thundray',
      'Toei Animation',
      'Toei Video',
      'Toho Interactive Animation',
      'Tokyo Kids',
      'Tokyo Media Connections',
      'Tokyo Movie',
      'Tokyo Movie Shinsha',
      'Tomason',
      'Tomovies',
      'Tomoyasu Murata Company',
      'Tonari Animation',
      'Tong Ming Xuan',
      'Tonko House',
      'Topcraft',
      'Trans Arts',
      'Transcendence Picture',
      'Trash Studio',
      'Tri-Slash',
      'TriF Studio',
      'Triangle Staff',
      'Trigger',
      'Trinet Entertainment',
      'TrioPen Studio',
      'Triple X',
      'Tryforce',
      'Tsubo Production',
      'Tsuburaya Productions',
      'Tsuchida Productions',
      'Tsukimidou',
      'Tsumugi Akita Animation Lab',
      'TthunDer Animation',
      'Twenty First',
      'Twilight Studio',
      'Twilight Town',
      'Twin Engine',
      'TypeZero',
      'Typhoon Graphics',
      'team Yamahitsuji',
      'teamKG',
      'trenova'
    ],
    U: [
      'UNKNOWN',
      'UWAN Pictures',
      'UchuPeople',
      'Uguisu Kobo',
      'Ultra Super Pictures',
      'Unend',
      'Urban Product',
      'Usagi Ou',
      'ufotable'
    ],
    V: [
      'V-sign',
      'VCRWORKS',
      'Vasoon Animation',
      'Vega Entertainment',
      'Venet',
      'View Works',
      'Visual 80',
      'Visual Flight',
      'Voil'
    ],
    W: [
      'W+K Tokyo',
      'W-Toon Studio',
      'WAO World',
      'WHOPPERS',
      'Wako Productions',
      'Wawayu Animation',
      'Wei Chuang Jiang Xin',
      'Welz Animation Studios',
      'White Fox',
      'Will Palette',
      'Wise Guy',
      'Wit Studio',
      'Wolf Smoke Studio',
      'Wolfsbane',
      'Wonder Cat Animation',
      'Wong Ping Animation Lab',
      'Wulifang Digital'
    ],
    X: [
      'XEBEC M2',
      'XFLAG',
      'XFLAG Pictures',
      'Xanthus Media',
      'Xebec',
      'Xing Yi Kai Chen',
      'Xuni Ying Ye'
    ],
    Y: [
      'Y.O.U.C',
      'YHKT Entertainment',
      'YURUPPE Inc.',
      'Yamamura Animation',
      'Yamato Works',
      'Yamiken',
      'Yaoyorozu',
      'Yi Chen Animation',
      'Yinhe Changxing Culture',
      'Yokohama Animation Lab',
      'Yonago Gainax',
      'Yostar Pictures',
      'Youku',
      'Yuhodo',
      'Yumeta Company',
      'yell'
    ],
    Z: ['Zero-G', 'Zero-G Room', 'Zexcs', 'Zyc']
  }

  return (
    <div className=" max-h-[70vh] overflow-y-auto">
      {Object.keys(list).map((letter) => (
        <Studio letter={letter} studios={list[letter]} />
      ))}
    </div>
  )
}

export default StudioList
